name: app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^1.1.0
  fast_immutable_collections: ^7.2.0
  nil: ^1.1.1
  dio: ^4.0.4
  dio_cache_interceptor: ^3.2.5
  flutter_riverpod: ^2.0.0-dev.3
  auto_route: ^3.2.4
  connectivity_plus: ^2.2.1
  path_provider: ^2.0.9
  isar: ^2.2.1
  isar_flutter_libs: ^2.2.1
  phone_numbers_parser: ^4.2.0
  sliding_up_panel: ^2.0.0+1
  shared_preferences: ^2.0.13
  auto_size_text: ^3.0.0
  modal_bottom_sheet: ^2.0.0
  easy_debounce: ^2.0.2+1
  dismissible_page: ^0.6.5
  flutter_blurhash: ^0.6.4
  permission_handler: ^9.2.0
  loading_animation_widget: ^1.1.0+1
  bubble_box: ^0.5.1
  pin_code_fields: ^7.3.0
  pinput: ^1.2.2
  json_annotation: ^4.4.0
  fluttertoast: ^8.0.9

  ovo_ui:
    path: packages/ovo_ui

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.0.4
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  auto_route_generator: ^3.2.3
  isar_generator: ^2.2.1
  json_serializable: ^6.1.3
  freezed: ^1.1.0
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
