name: app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  auto_size_text: ^3.0.0
  bubble_box: ^0.5.1
  connectivity_plus: ^2.2.1
  dio: ^4.0.4
  dio_cache_interceptor: ^3.2.5
  dismissible_page: ^0.7.2
  easy_debounce: ^2.0.2+1
  fast_immutable_collections: ^7.2.0
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.7.0
  flutter_bounceable: ^1.0.2
  flutter_custom_tab_bar: ^1.1.9
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.4
  flutter_secure_storage: ^5.0.2
  flutter_staggered_animations: ^1.0.0
  flutter_staggered_grid_view: ^0.6.1
  fluttertoast: ^8.0.9
  freezed_annotation: ^2.0.3
  gesture_x_detector: ^1.0.0
  image_crop:
    path: packages/image_crop
  intl: ^0.17.0
  json_annotation: ^4.4.0
  loading_animation_widget: ^1.1.0+1
  modal_bottom_sheet: ^2.0.0
  nil: ^1.1.1
  ovo_ui:
    path: packages/ovo_ui
  path: ^1.8.0
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  phone_numbers_parser: ^5.0.5
  photo_manager: ^2.0.0-dev.13
  pin_code_fields: ^7.3.0
  pinput: ^2.2.9
  sembast: ^3.2.0
  sliding_up_panel: ^2.0.0+1
  syncfusion_flutter_sliders: ^20.1.56
  vertical_weight_slider: ^2.4.0
  video_player: ^2.2.19

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.7
  dart_code_metrics: ^4.11.0
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1

  flutter_native_splash: ^2.0.4
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.1.3
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
